## **Python Basics**

This codes are from Miuul_Data Analyst Bootcampl
by Atilla Yardımcı

In [1]:
# First Code

3 + 3

6

In [2]:

4/3

1.3333333333333333

In [3]:
# Value

3.2

3.2

In [4]:
a = 3

In [5]:
type(a)

int

In [6]:
a = 9

In [7]:
b = 10

In [8]:
a*b

90

In [9]:
print("Python")

Python


In [10]:
a = input()

3


In [11]:
print("My Favourite Number is :", 4)

My Favourite Number is : 4


In [5]:
#Reading Data
a = input()

print(a)

3
3


In [1]:
# Methods

type("hello")

str

In [2]:
type(3)

int

In [3]:
type(3.2)

float

In [6]:
type(a)

str

In [7]:
info = "Assignment Operations"

In [9]:
type(info)

str

In [10]:
info.upper()

'ASSIGNMENT OPERATIONS'

In [11]:
info.lower()

'assignment operations'

In [12]:
info.replace("s", "t")

'Attignment Operationt'

In [13]:
info = info.upper()

In [14]:
info

'ASSIGNMENT OPERATIONS'

In [15]:
info.upper().replace("a","e")

'ASSIGNMENT OPERATIONS'

In [16]:
info

'ASSIGNMENT OPERATIONS'

In [17]:
"ESIN".lower()

'esin'

In [18]:
info.isupper()

True

### Data Types

In [19]:
# Data Types & Integer

In [20]:
x = 18

In [21]:
type(x)

int

In [22]:
y = 4.2

type(y)

float

In [23]:
# # Data Types & Integer

a = "Hello World"

type(a)

str

### List

In [24]:
my_list = [3,3,4,"a",True]

In [25]:
my_list

[3, 3, 4, 'a', True]

In [26]:
len(my_list)

5

In [28]:
my_list[2] #Second Index

4

In [30]:
my_list[3] #Third Index

'a'

In [31]:
my_list[2:4]

[4, 'a']

In [32]:
my_list[3] = "Esin like eationg cake"

In [33]:
my_list

[3, 3, 4, 'Esin like eationg cake', True]

### Tuple

In [34]:
my_tuple = (3,3,4,"a")

In [35]:
my_tuple

(3, 3, 4, 'a')

### Set

In [36]:
my_set= {2,3,"a"}

In [37]:
my_set

{2, 3, 'a'}

### Dictionary

In [38]:
my_dict =  { "Name" : "Arda", 
             "Age"  : 40 }

In [39]:
my_dict

{'Name': 'Arda', 'Age': 40}

In [40]:
my_dict.keys()

dict_keys(['Name', 'Age'])

In [41]:
my_dict.values()

dict_values(['Arda', 40])

### List Practises

In [42]:
text = "Once you stop learning, before you dying."

In [43]:
text.upper()

'ONCE YOU STOP LEARNING, BEFORE YOU DYING.'

In [44]:
text.replace(" ", "_")

'Once_you_stop_learning,_before_you_dying.'

In [45]:
text.split()

['Once', 'you', 'stop', 'learning,', 'before', 'you', 'dying.']

In [46]:
text

'Once you stop learning, before you dying.'

In [47]:
text.upper().replace(" ", "_").replace(".","$$$$")

'ONCE_YOU_STOP_LEARNING,_BEFORE_YOU_DYING$$$$'

In [48]:
my_list = ["D","A","T","A","S","C","I","E","N","C","E"]

In [49]:
my_list

['D', 'A', 'T', 'A', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [50]:
type(my_list)

list

In [51]:
my_list_2 = "DATA SCIENCE"

In [52]:
type(my_list_2)

str

In [53]:
len(my_list)

11

In [56]:
my_list[6]

'I'

In [59]:
my_list[2:4] +my_list[2:4]

['T', 'A', 'T', 'A']

In [60]:
my_list.insert(4,"A")

In [61]:
my_list

['D', 'A', 'T', 'A', 'A', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [62]:
my_list = [1,2,3,[10,20,30],4]

In [63]:
my_list[3][2]

30

In [64]:
my_list[2:]

[3, [10, 20, 30], 4]

In [66]:
date = ["25","09","2022"]
"/".join(date)

'25/09/2022'

### For Loops

In [68]:
for u in [3,4,5,7]:
    print(u)

3
4
5
7


In [69]:
for u in [3,4,40,41]:
    u=u+1
    print(u)

4
5
41
42


In [70]:
for u in ["Age","Gender","Income","City"]:
    print(u)

Age
Gender
Income
City


In [71]:
a = 0

for d in [3,4,40]:
    a = a+ d
    
print(a)

47


In [73]:
x = range(0, 10, 2)

for n in x:
    print(n)

0
2
4
6
8


### Functions

In [74]:
def learning_for(a,b,c):
    x = range(a,b,c)
    for n in x:
        print(n)

In [75]:
learning_for(a,b,c)

NameError: name 'b' is not defined

In [76]:
learning_for(4,5,6)

4


In [78]:
def sum_functions():
    
    print("The first number: ")
    
    num1 = int(input())
    
    print("The second number: ")
    
    num2 = int(input())
    
    print("Total: ",  num1 + num2)
    

In [80]:
sum_functions()

The first number: 
4
The second number: 
5
Total:  9


## Numpy

In [81]:
a = [10,20,30,40]
b = [22,23,24,25]

In [82]:
len(a)

4

In [83]:
b[3]

25

In [84]:
ab = []

In [85]:
ab

[]

In [86]:
ab.append(3)

In [87]:
ab

[3]

In [88]:
range(0, len(a))

range(0, 4)

In [89]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i] + b[i])
    
ab

[32, 43, 54, 65]

In [90]:
import numpy as np

In [91]:
a = np.array([10,20,30,40])
b = np.array([22,23,24,25])

In [92]:
a

array([10, 20, 30, 40])

In [93]:
b

array([22, 23, 24, 25])

In [94]:
a = np.array([1,2,3,4,5,6,7,8,9,22,33,44,55])

In [95]:
a>30

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True])

In [96]:
a[a<30]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 22])

In [99]:
a[(a<30) | (a > 60)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 22])

In [100]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 22, 33, 44, 55])

In [101]:
x = 40
y = 50

if x>y:
    print(x)
else:
    print(y)

50


In [102]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 22, 33, 44, 55])

In [105]:
ab = []

for i in a:
    if i > 70:
        ab.append(i)

In [106]:
ab

[]

## Pandas

In [107]:
import pandas as pd

In [108]:
my_list = [10,20,30,40]

In [109]:
my_list

[10, 20, 30, 40]

In [110]:
pd.DataFrame(my_list, columns = ["Age"])

Age
0   10
1   20
2   30
3   40

In [111]:
m = [[1,2,3],[4,5,6],[7,8,9]]

In [112]:
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [113]:
pd.DataFrame(m, columns = ["Age1","Age2","Age3"])

Age1  Age2  Age3
0     1     2     3
1     4     5     6
2     7     8     9

In [114]:
df = pd.DataFrame(m, columns = ["Age1","Age2","Age3"])

In [115]:
df

Age1  Age2  Age3
0     1     2     3
1     4     5     6
2     7     8     9

In [116]:
import seaborn as sns

In [118]:
df = sns.load_dataset("car_crashes")

In [119]:
df

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0    18.8     7.332    5.640          18.048       15.040       784.55   
1    18.1     7.421    4.525          16.290       17.014      1053.48   
2    18.6     6.510    5.208          15.624       17.856       899.47   
3    22.4     4.032    5.824          21.056       21.280       827.34   
4    12.0     4.200    3.360          10.920       10.680       878.41   
5    13.6     5.032    3.808          10.744       12.920       835.50   
6    10.8     4.968    3.888           9.396        8.856      1068.73   
7    16.2     6.156    4.860          14.094       16.038      1137.87   
8     5.9     2.006    1.593           5.900        5.900      1273.89   
9    17.9     3.759    5.191          16.468       16.826      1160.13   
10   15.6     2.964    3.900          14.820       14.508       913.15   
11   17.5     9.450    7.175          14.350       15.225       861.18   
12   15.3     5.508    4.437          13.005       14.994       641.96   
13   12.8     4.608    4.352          12.032       12.288       803.11   
14   14.5     3.625    4.205          13.775       13.775       710.46   
15   15.7     2.669    3.925          15.229       13.659       649.06   
16   17.8     4.806    4.272          13.706       15.130       780.45   
17   21.4     4.066    4.922          16.692       16.264       872.51   
18   20.5     7.175    6.765          14.965       20.090      1281.55   
19   15.1     5.738    4.530          13.137       12.684       661.88   
20   12.5     4.250    4.000           8.875       12.375      1048.78   
21    8.2     1.886    2.870           7.134        6.560      1011.14   
22   14.1     3.384    3.948          13.395       10.857      1110.61   
23    9.6     2.208    2.784           8.448        8.448       777.18   
24   17.6     2.640    5.456           1.760       17.600       896.07   
25   16.1     6.923    5.474          14.812       13.524       790.32   
26   21.4     8.346    9.416          17.976       18.190       816.21   
27   14.9     1.937    5.215          13.857       13.410       732.28   
28   14.7     5.439    4.704          13.965       14.553      1029.87   
29   11.6     4.060    3.480          10.092        9.628       746.54   
30   11.2     1.792    3.136           9.632        8.736      1301.52   
31   18.4     3.496    4.968          12.328       18.032       869.85   
32   12.3     3.936    3.567          10.824        9.840      1234.31   
33   16.8     6.552    5.208          15.792       13.608       708.24   
34   23.9     5.497   10.038          23.661       20.554       688.75   
35   14.1     3.948    4.794          13.959       11.562       697.73   
36   19.9     6.368    5.771          18.308       18.706       881.51   
37   12.8     4.224    3.328           8.576       11.520       804.71   
38   18.2     9.100    5.642          17.472       16.016       905.99   
39   11.1     3.774    4.218          10.212        8.769      1148.99   
40   23.9     9.082    9.799          22.944       19.359       858.97   
41   19.4     6.014    6.402          19.012       16.684       669.31   
42   19.5     4.095    5.655          15.990       15.795       767.91   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
44   11.3     4.859    1.808           9.944       10.848       809.38   
45   13.6     4.080    4.080          13.056       12.920       716.20   
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
0       145.08     AL  
1       133.93     AK  
2       110.35     AZ  
3       142.39     AR  
4       165.63     CA  
5       139